# Generated by Django 4.0.4 on 2022-04-14 11:25

from django.db import migrations, models
import django.db.models.deletion
import froala_editor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Keypoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('Sno', models.AutoField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetured_image', models.ImageField(upload_to='Images')),
                ('alt_tag', models.CharField(max_length=150)),
                ('title', models.CharField(max_length=200)),
                ('author', models.CharField(max_length=50)),
                ('author_image', models.ImageField(upload_to='Images')),
                ('author_content', models.CharField(max_length=500)),
                ('date', models.DateField(auto_now_add=True)),
                ('content', froala_editor.fields.FroalaField()),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
                ('meta_title', models.CharField(max_length=65)),
                ('meta_descripations', models.CharField(max_length=150)),
                ('meta_keywords', models.CharField(max_length=65)),
                ('status', models.CharField(choices=[('0', 'Draft'), ('1', 'Publish')], max_length=100)),
                ('section', models.CharField(choices=[('Home', 'Home'), ('featured', 'featured'), ('Recent', 'Recent'), ('upcomingRides', 'upcomingRides')], max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.category')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myblog.post')),
            ],
        ),
    ]
