# Generated by Django 4.0.5 on 2022-06-22 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='file_pdf',
            field=models.ImageField(default=None, upload_to='media/pdfs'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_content',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='author_image',
            field=models.ImageField(blank=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='fetured_image',
            field=models.ImageField(blank=True, upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='section',
            field=models.CharField(choices=[('Home', 'Home'), ('featured', 'featured'), ('Recent', 'Recent'), ('Frettir', 'Frettir')], max_length=100),
        ),
    ]
