# Generated by Django 4.0.5 on 2022-06-22 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0002_contact_file_pdf_alter_post_author_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author_content',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author_image',
        ),
    ]
