# Generated by Django 4.0.5 on 2022-06-22 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0003_remove_post_author_content_remove_post_author_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='file_pdf',
            field=models.ImageField(default=False, upload_to='media/pdfs'),
        ),
    ]
