# Generated by Django 4.0.5 on 2022-06-22 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0012_alter_contact_file_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='file_pdf',
            field=models.FileField(default='Images/28532.jpg', upload_to='Images'),
        ),
    ]
